### ISSUE TITLE
How do I even refactor to this?

### ISSUE THREAD

**Issue by bobthemighty** [cosmicpython/book#10]
Refactoring from an existing BBOM.

**Comment by bobthemighty** [comment]
Migrating with the strangler pattern and event capture and all that jazz

**Comment by hjwp** [comment]
DS quote:

> There's nothing in the book about how to migrate to the pattern described here. I would have thought target readers are likely to be working on an existing project that isn't scaling well - how do they begin to apply these principles to existing architecture. Perhaps some advice on how to begin if you have (a) traditional three layer architecture or (b) big ball of mud.

**Comment by hjwp** [comment]
could be an epilogue chapter?
