### ISSUE TITLE
Chapter 7 Synchronous Message Bus Handlers

### ISSUE THREAD

**Issue by jonathanmeier5** [cosmicpython/book#102]
Everything you guys wrote in Chapter 7 indicates that the event handler is synchronous, but my expectation that event handlers will be async was so strong that I needed to re-read the chapter a few times before I could intuitively understand it as a synchronous system.

It might be worth mentioning explicitly/in English somewhere in the middle of the chapter that this is a synchronous system.

**Comment by hjwp** [comment]
We now draw attention to this several times :)

eg https://github.com/cosmicpython/book/blob/master/chapter_07_events_and_message_bus.asciidoc#the-message-bus-maps-events-to-handlers

closing.  Hey Jonathan, if you fancy taking another look at the book, we've reorganised the event-driven chapters, added some detail on commands vs events and error handling, fleshed out the chapters on cqrs and dependency injection, and added a couple of good appendices on bootstrap scripts and validation...  all good stuff, but sorely in need of Jonathan-feedback...
