### ISSUE TITLE
Chapter 8 Domain Object/Primitives/Event Discussion

### ISSUE THREAD

**Issue by jonathanmeier5** [cosmicpython/book#103]
You guys already have a TODO for discussing the process of moving from domain objects to primitives to events, but I wanted to indicate interest in the topic.

In particular, I'm curious to hear about scenarios where you think using primitives might be a superior alternative to moving to a full-blown event driven system. Obviously a good chunk of the second half of the book is dedicated towards exploring the strengths of the event driven system, but is it always superior?

**Comment by hjwp** [comment]
Hi Jonathan, we've started adding some explicit discussion of tradeoffs at the end of each chapter.  see the commit above, also this bit in chap 9 https://github.com/cosmicpython/book/blob/master/chapter_08_all_messagebus.asciidoc#why-have-we-achieved

and this bit in the very first events chapter https://github.com/cosmicpython/book/blob/master/chapter_07_events_and_message_bus.asciidoc#wrap-up

**Comment by hjwp** [comment]
i'm going to arrogantly assume we've covered your question and close this, but will you reopen if you think there are some questions we haven't really addressed, or bits you'd like to see more detail on?
