### ISSUE TITLE
Service layer VS domain service

### ISSUE THREAD

**Issue by haibin** [cosmicpython/book#127]
I think we don't quite get what the domain service is, especially in chapter 4. In chapter 4, domain service `allocate` looks like below.

```python
def allocate(line: OrderLine, batches: List[Batch]) -> str:
    try:
        batch = next(
            b for b in sorted(batches) if b.can_allocate(line)
        )
        batch.allocate(line)
        return batch.reference
    except StopIteration:
        raise OutOfStock(f'Out of stock for sku {line.sku}')
```

Can we move the whole thing to service layer? What are the pros and cons?

**Comment by bobthemighty** [comment]
Service is one of the most overloaded words in computer science, so I'm sorry about that.

We're using two distinct kinds of "service" in the text: an application service (usually called a _handler_) is a component that receives requests from the outside world and orchestrates a business process by, eg. fetching some object from the orm, calling a method on it, and committing the resulting state; while a domain service is a component that encapsulates some complex calculation that belongs in the domain model but doesn't sit naturally inside a stateful entity.

**Comment by bobthemighty** [comment]
The _cons_ of mixing the two are that you end up with orchestration logic and business logic mixed up, and that makes it harder to test and evolve the system over time.

**Comment by hjwp** [comment]
we've got a bit of disambiguation now in this section https://github.com/cosmicpython/book/blob/master/chapter_04_service_layer.asciidoc#why-is-everything-called-a-service
