### ISSUE TITLE
talk about exception handling

### ISSUE THREAD

**Issue by hjwp** [cosmicpython/book#131]
> (DS): More generally I'd be interested in some general principles about handling exceptions in a layered architecture...

we'll have some good chat about it in part 2 once #123 gets merged, but would be good to say something in part 1 as well.

**Comment by hjwp** [comment]
gonna close this as i'm hoping the examples of domain + service-layer exceptions bubbling up to flask, plus the error-handling chat in the messagebus command handler bits are enough hopefully? @seddonym, do reopen if you think this deserves more speicific treatment

**Comment by sobolevn** [comment]
I would also ask if mentioning `Result` is worth it. This is a completely separate mechanism of handling exceptions. 

There are several important things inside:
1. Railway oriented programming: https://fsharpforfunandprofit.com/rop/
2. Type safety: you can always know if your function raises or not
3. It is not really common in Python, so people might know something new (in contrast to other languages where Haskell / F3 / Rust there are almost no other options)
4. It works perfectly with domain exceptions and regular ones

There's an example here: https://returns.readthedocs.io/en/latest/pages/result.html
