### ISSUE TITLE
Questions on the change_batch_quantity in chapter 5

### ISSUE THREAD

**Issue by haibin** [cosmicpython/book#134]
In chapter 5, I don't know understand the code below.

```python
def change_batch_quantity(batchref: str, new_qty: int, uow: AbstractUnitOfWork):
    with uow:
        batch = uow.batches.get(reference=batchref)
        batch.change_purchased_quantity(new_qty)
        while batch.available_quantity < 0:
            line = batch.deallocate_one()  #(1)
        model.allocate(line)
        uow.commit()
```

Should `model.allocate(line)` be in the while loop?

**Comment by hjwp** [comment]
no, that doesn't make any sense, you're right.  will fix it.  (is one of the untested code listings because it's not in the main dev story of the book you see)

**Comment by hjwp** [comment]
i think just removing it makes sense to keep this listing simple -- we want to show that we will deallocate any number of lines, and the `uow` make sure we either do all of them, or none, if an exception is raised by any given `deallocate_one()` call...
