### ISSUE TITLE
Why is eta is Optional in chapter 1

### ISSUE THREAD

**Issue by haibin** [cosmicpython/book#137]
One question: Since eta does not have a default value, why is it optional?

```python
class Batch:
    def __init__(
        self, ref: str, sku: str, qty: int, eta: Optional[date]  #(2)
    ):
        self.reference = ref
        self.sku = sku
        self.eta = eta
        self.available_quantity = qty

    def allocate(self, line: OrderLine):
        self.available_quantity -= line.qty  #(3)
```

**Comment by hjwp** [comment]
good question! `typing.Optional` isn't quite the same as saying an argument is optional, it's actually saying that something may be None - https://docs.python.org/3/library/typing.html#typing.Optional
