### ISSUE TITLE
In chapter 7 question on products.seen

### ISSUE THREAD

**Issue by haibin** [cosmicpython/book#140]
Can you explain the reason for having this `products.seen`? What would be the issue without it?

**Comment by hjwp** [comment]
In this section https://github.com/cosmicpython/book/blob/master/chapter_07_events_and_message_bus.asciidoc#the-unit-of-work-can-publish-events-to-the-message-bus

we show `products.seen` in use on the `AbstractRepository`.  callout `#(3)` explains why:

> That relies on the repository keeping track of aggregates that have been loaded using a new attribute, `.seen`, as we’ll see in the next listing.

It's not obvious though. I'll try and reinforce that point by calling back to it a second time somewhere in the text...

**Comment by hjwp** [comment]
:point_up: does that help?
