### ISSUE TITLE
no BatchQuantityChanged instances in chapter 8 code

### ISSUE THREAD

**Issue by haibin** [cosmicpython/book#141]
I tried to understand the difference between AllocationRequired and BatchQuantityChanged, but found nowhere in the code (https://github.com/cosmicpython/code/tree/chapter_08_all_messagebus) `BatchQuantityChanged` was being instantiated except in the tests.

I must have missed something.

**Comment by hjwp** [comment]
ah yes, that's because we only actually start using it in the next chapter.  let me add a note..
