### ISSUE TITLE
Chapter 3: repeated paragraph

### ISSUE THREAD

**Issue by ivergara** [cosmicpython/book#148]
In chapter 3, there are two paragraphs that are basically the same

> Now we need to write the bit that makes decisions about what to do. When we have to tackle a problem from first principles, we usually try to write a simple implementation, and then refactor towards better design. We’ll use this approach throughout the book, because it’s how we write code in the real world: start with a solution to the smallest part of the problem, and then iteratively make the solution richer and better designed.
> 
> Now we need to write the interesting business logic. When we have to tackle a problem from first principles, we usually try to write a simple implementation, and then refactor towards better design. We’ll use this approach throughout the book, because it’s how we write code in the real world: start with a solution to the smallest part of the problem, and then iteratively make the solution richer and better designed.

**Comment by hjwp** [comment]
thanks for this too!  how did you find the chapter?  are you planning to read the rest of the book?  we're very interested in feedback.   especially in the next few weeks, before we go to print in Jan!

**Comment by ivergara** [comment]
I did find it by reading through from the beginning. I'm planning to keep reading, but not sure the rhythm at the moment (end of the year is always crazy). I'll keep pointing to glaring things as I continue reading.
