### ISSUE TITLE
Project Structure

### ISSUE THREAD

**Issue by pedroabi** [cosmicpython/book#159]
I have seen that "allocation" folder looks like a bounded context. I suppose that for an application with multiple bounded context I should create another folder inside "src" folder.
src
  - allocation
  - order (for e.g.)

Is that correct ? How could I handle shared entities between bounded context? Should I have one UOW into each of the bounded context? Or should I place a UOW in a shared context?

**Comment by hjwp** [comment]
closing in favour of #64
