### ISSUE TITLE
Persisting Events

### ISSUE THREAD

**Issue by daniel-butler** [cosmicpython/book#240]
I can’t say it enough I love the book and mention it anytime I can. 

How would you go about persisting events? I’m thinking of if someone wants to look up a Product aggregate how could they see the events that occurred after the code restarts? Or at a high level how would it be implemented,  hooking it into the unit of work, messagebus or something else?

**Comment by daniel-butler** [comment]
Would it make sense to have a handler that takes a given event and saves it to the database. Then add it to the beginning of every event's `EVENT_HANDLER`?

**Comment by hjwp** [comment]
two breadcrumbs here:

1. chapter 11 (on external events) says you can use events for integration, and then you publish them to an external message bus / message broker. depending on what broker you choose, it may have some sort of persistence.  at MADE we use Event Store for example, which stores events forever

2. you can flip this whole thing on its head by using a technique called "event sourcing", where the *only* thing you store in the database is events, and your reconstruct the current state of your domain model by reading the history of all events pertaining to it.  bob explanation here: https://www.youtube.com/watch?v=0l8vuYaaBUs  https://github.com/bobthemighty/eventsourcing-101

**Comment by xtaje** [comment]
As a third breadcrumb, the epilogue also links to a description of the [Outbox Pattern](https://microservices.io/patterns/data/transactional-outbox.html), which is a more lightweight option than changing to a different message broker, or doing event sourcing.  If you were to implement an event store yourself, you would probably end up doing something very similar to Outbox.  IIRC Vaughn Vernon's red book has an example of this in the appendix.

Just adding a handler that does nothing but event persistence would create the problem where the events are persisted outside the UOW/transaction.  I believe that would introduce a lot of edge cases around event ordering and dropping events.

**Comment by daniel-butler** [comment]
Thank you both!

Breadcrumbs
1. I would like to limit (at this time) the number of systems the code is dependent on. Also I have to develop in Windows which limits what I can do :(
2. Making the events the star sounds like what this library is all about https://github.com/johnbywater/eventsourcing which is totally viable, if starting from scratch. 
3. I think that is what I originally suggested except that the code then looks at this event data to process events as they happen. Is that correct?

When it comes to persisting events, does it make sense to have a unique id like a `uuid4` that is generated for all commands and is passed down to the related events? I’ve been asked to send emails with information that can’t be easily queried with a cqrs model without knowing what is linked to a specific command. The example would be someone orders a product but it generates one or more shipments and the end user wants to know how many shipments they generated. When persisting the events with an id that ties to a given command then a view looking up the domain events by the id should give the information needed. Just wondering if you see any holes or common pitfalls with that approach.

**Comment by hjwp** [comment]
the main difference between your suggestion (a handler called eg `persist_event` that's called for all events) vs outbox pattern is that outbox pattern wants the events to be persisted _in the same transaction_.  so you wouldn't implement outbox pattern using a handler, maybe in the uow or in the ORM somehow instead.  so it depends, as ed says, about how worried you are about edge cases around event ordering and dropping events.

re: uuids for events people often use what's called "correlation ids" (and sometimes also distinguish separate "causation ids") - the first couple of paragraphs in this blog, and the diagram, do quite a good job of explaining them: https://blog.arkency.com/correlation-id-and-causation-id-in-evented-systems/

**Comment by xtaje** [comment]
Another idea -- It seems to me that you would want to correlate shipments to an order aggregate, as opposed to a command.  So you could just add references to `Shipments` to your  `Orders`, and have an event `ItemShipped`, plus a handler that will update the `Order` aggregate.  Alternatively, maybe you could introduce the concept of a `Fulfillment` which tracks the relation between `Order` and `Shipment` instances.  In either case, it would avoid extra complexities around persisting events.

**Comment by daniel-butler** [comment]
I love the correlation ids idea. It answers questions that will be asked, but didn’t realize until reading. 

Would it make sense to add another id that relates to a specific web request? The article seems like it’s concern is isolated to inside the related code not the systems around it. I may have interrupted that wrong. Adding another id to tie to a web request or external system command/event id seems like a good idea.  It gives the ability to measure overall response time, visibility into why and where commands or events are initiated. However; I can’t tell if it is a real blind spot or engineering overkill. Hopefully I’m not going to far down the rabbit hole! You’ve both been very helpful and thought provoking. 

@xtaje what it sounds like you are saying is I should abstract up another level or don’t have the domain modeled correctly. The feature requests being asked leads me to believe the model does not fully represent the domain. Which I should probably take as a code smell. Essentially trying to use the command id as another domain entity. Going the route of making the command id a reference point seems like tight coupling to the persistence implementation detail. 

On the original topic, the more I’m chewing on what you’ve both said, I should bite the bullet  Send events to a messagebus/store like event store whiling fixing the model for the domain.  Event Store persists events while opening possibilities for even more interactions.

**Comment by hjwp** [comment]
going to close this now, hope that's OK Daniel.

**Comment by simkimsia** [comment]
Great thread! My two cents are that this issue and my similar question at #306 should be considered as the expanded material for a 2nd ed of the book.
