### ISSUE TITLE
ch9 figures 9.1 and 9.2 are identical

### ISSUE THREAD

**Issue by jbasko** [cosmicpython/book#263]
(I already reported this on O'Reilly errata, but then noticed this repo). Maybe I'm blind, but it appears to me figures 9.1 and 9.2 are identical.

**Comment by hjwp** [comment]
no, you were absolutely right.  thanks so much for reporting it.

how are you finding the rest of the book?

**Comment by jbasko** [comment]
The book is awesome. I think this will be big. Thank you for filling the big void in this part of the Python world. Enough of Django Driven Development.

**Comment by hjwp** [comment]
awesome thanks.  if you feel inclined, will you leave a review on the safari site?  and do let us know about any other comments or suggestions or bugfixes!

**Comment by jbasko** [comment]
done!

**Comment by hjwp** [comment]
I saw it! thanks so much Jazeps, it was a lovely review :-)

**Comment by hjwp** [comment]
Bob and I particularly enjoyed this line:

> I liked that the two authors had different views on what kind of code is permitted in Python. I lean more towards Bob’s verbosity, but who knows what would all this look like if Harry had not stopped him. So hats off to both!
