### ISSUE TITLE
Chapter 2: Typo, or something in python I don't understand

### ISSUE THREAD

**Issue by Chris-May** [cosmicpython/book#266]
I'm trying to digest my way through the book, and I realized I skipped this before, but I wanted to ask, in case I'm missing something.

Example 10. Repository test for retrieving a complex object (test_repository.py)
```
def insert_order_line(session):
    session.execute(  #(1)
        'INSERT INTO order_lines (orderid, sku, qty)'
        ' VALUES ("order1", "GENERIC-SOFA", 12)'
    )
    [[orderline_id]] = session.execute(
        'SELECT id FROM order_lines WHERE orderid=:orderid AND sku=:sku',
        dict(orderid="order1", sku="GENERIC-SOFA")
    )
    return orderline_id
```

Line 648 is this:
```
    [[orderline_id]] = session.execute(
```
I don't recognize this "double list" syntax. Is this something neat in python, or is it just a typo?

**Comment by Chris-May** [comment]
Is it pulling out a nested object? Like pulling out the orderline_id from inside a sqlalchemy object?

**Comment by hjwp** [comment]
it is something neat in python, i'm afraid I had a weak moment and fell for the lure of writing "clever-clever" code.  I think the technical name is "iterable unpacking".  trey has a good explanation here: https://treyhunner.com/2018/03/tuple-unpacking-improves-python-code-readability/

**Comment by hjwp** [comment]
session.execute returns a list of (one) rows, and each row is a tuple with, in this case, one element, so the right and left hand side have the same structure, if that makes sense

**Comment by Chris-May** [comment]
Thanks, Harry!
It's been a surprisingly long time since I used SQLAlchemy. But you betcha I'm going to use that trick next time I do!!!
