### ISSUE TITLE
the example abt raw SQL should be referring to the chapter 12 and not 11 yes?

### ISSUE THREAD

**Issue by simkimsia** [cosmicpython/book#275]
# Summary

Reference to another chapter in epilogue appears to be wrong

## Description
 Under https://github.com/cosmicpython/book/blob/master/epilogue_1_how_to_get_there_from_here.asciidoc#identifying-aggregates-and-bounded-contexts

the line (sorry somehow github webview for asciidoc does not allow me to cite the exact line as a url)

Tip | We use this same technique in [chapter_11_external_events], where we replace a nested loop over ORM objects with a simple SQL query. It’s the first step in a CQRS approach.
-- | --

But there's no example of SQL query in chapter 11.

## Expected

i think it should refer to chapter 12 specifically the raw query in the subsection hold on to your lunch folks
https://github.com/cosmicpython/book/blob/master/chapter_12_cqrs.asciidoc#hold-on-to-your-lunch-folks

**Comment by hjwp** [comment]
thanks so much!
