### ISSUE TITLE
Serialize data into nested dictionaries of values: where to do it?

### ISSUE THREAD

**Issue by simkimsia** [cosmicpython/book#277]
Summary: How to transform data for read operations  into nested dictionaries of values

## What I understand

So there's a nice diagram about using _View Builder_ and _View Fetcher_ in epilogue. 

![view builder diagram](https://raw.githubusercontent.com/cosmicpython/book/master/images/apwp_ep06.png)

There's also a nice diagram about before and after modeling with aggregates in the same epilogue chapter which splits Document, Workspace all into their own individual aggregates. 

![before after](https://raw.githubusercontent.com/cosmicpython/book/master/images/apwp_ep03.png)

However, let's say i have a read operation that's expected to have nested dictionary of values.

## What I want to do

Suppose the read operation returns the nested structure of Document as per the 2nd diagram above as a dictionary of values

```json
{
  "id": document.id,
  "workspace_id": document.workspace_id,
  "parent_folder": document.parent_folder,
  "versions": [
       {
           "id": first_version.id,
           "title": first_version.title,
           "version_number": 1,
       },
       {
           "id": sec_version.id,
           "title": sec_version.title,
           "version_number": 2,
       }
   ],
}
```

And for some reason, let's say the django API endpoint is so slow, that there are two places that are slow.

1. The query itself
2. and the serialization

So I want to write my own raw query and my own serializers.

Do I write the raw query under _View Fetcher_ and the serializers under _View Builder_?

Thank you

**Comment by hjwp** [comment]
I think yes! the idea being that you can swap the view fetcher out with a fake version in order to unit test the view builder.  but I would only bother splitting out those two halves if the data transformations in the view builder were complex, and had lots of edge cases. otherwise a single view component with integration tests feels like enough. see chapter 12...

**Comment by simkimsia** [comment]
Query answered hence closed

**Comment by hjwp** [comment]
how are you enjoying the book in general?

**Comment by simkimsia** [comment]
@hjwp Sorry just saw your question

I enjoy it very much. It's something I always wanted but cannot articulate in my mind. Even as a developer more familiar with Django, this is a much needed book.

The book has also inspired me to purchase more books regarding DDD, more event-driven architecture.

the blue DDD & the sam newman's from monoliths to microservices just arrived a couple days ago.

I bought them based on the recommendations inside cosmicpython

I think this book serves as a good entrypoint to a highly multifaceted and integrated approach for complex web app built using modern web tech and practices. It's good compression of various different but related ideas (DDD, eventdriven etc) but also encourages people like me to use it as a launchpad to go deeper into those ideas.

**Comment by simkimsia** [comment]
In case, I miss out on your future notifications, do @ me or hit me on twitter at https://twitter.com/KimStacks 

Thanks
