### ISSUE TITLE
Chapter 8 - duplicate content ?

### ISSUE THREAD

**Issue by adrienbrunet** [cosmicpython/book#282]
# Chapter 8 - Events and the Message Bus
## Avoid Making a Mess
...
### And let's Not Make a Mess of Our Moodel Either
The domain model's job is to know [....] without needing to change the rules of our domain model.

## Single Resposibility Principles
The domain model's job is to know [....] without needing to change the rules of our domain model.

These sentences are for sure important but they are separate apart by one page. Maybe be we can get rid off one.

> Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.

**Comment by hjwp** [comment]
:smiley:
