### ISSUE TITLE
Production deployment

### ISSUE THREAD

**Issue by mck-user580** [cosmicpython/book#287]
I wanted to see if you had any recommendations on production deployment structure/tools (how to package, structure for docker deployment, any pythonic tools that are best at this) in 2020. Examples would be great too.

If there is an existing post covering this question, would love a link.

Thank you

**Comment by hjwp** [comment]
I'm afraid I don't have anything good to point you to.  Deployment varies so much on a case-by-case basis...  

if you haven't seen it already, the "appendix project structure" has lots of suggestions on how to structure the project in general.  but it stops short of deployment, beyond leaving you with a dockerized / 12-factorable app...

**Comment by hjwp** [comment]
https://www.cosmicpython.com/book/appendix_project_structure.html

**Comment by hjwp** [comment]
(am closing this for now, but do reopen if you find a resource you think we should include in the book)

how are you enjoying the book in general, by the way?

**Comment by mck-user580** [comment]
I think the book is great. Purchased my own copy. I think python community needed a book like this - to be honest. My background is from enterprise/soa/microservices arch in java (java bias) into deploying some flask/python based APIs.
Thank you!

**Comment by hjwp** [comment]
:smile: thanks!

if you have a moment, will you write up a short review on amazon, or wherever you bought it?
