### ISSUE TITLE
[Question] Product in two different bounded contexts / services can refer to same datatable?

### ISSUE THREAD

**Issue by simkimsia** [cosmicpython/book#294]
Context first:

I am primarily using Django which is Active Record ORM pattern. So 1 Django model is one datatable.

I read in https://www.cosmicpython.com/book/chapter_07_aggregate.html#bounded_contexts_sidebar

> This concept translates very well to the world of microservices, where each microservice is free to have its own concept of "customer" and its own rules for translating that to and from other microservices it integrates with.
>
> In our example, the allocation service has Product(sku, batches), whereas the ecommerce will have Product(sku, description, price, image_url, dimensions, etc…​). As a rule of thumb, your domain models should include only the data that they need for performing calculations.

This is an elegantly and obvious-on-hindsight great idea. Now I am thinking how do I implement something like this?

Let's say that I add an additional forced requirement that the Product has its own datatable and has a field called `batch_count` int and their relations are that Product hasMany Batch and Batch belongsToOne Product.

so when you run `add_batch`, the field in the Product datatable should increment. So can the Product in the `allocation` service/bounded context update to the same datatable?

I like to ask how you would do this:

1. in Flask
2. in Django (if not possible, or you're unsure, it's fine)

**Comment by hjwp** [comment]
(am assuming that by "datatable" you mean a table in a database, is that right?)

there are two different ways you can approach bounded contexts.  one is to have a different microservice (and a different database) for each service.   in that case you have to figure out how to keep the two in sync, and we tend to recommend using something based on asynchronous messaging, external events with a message broker.

alternatively, you can different bounded contexts within the same app/monolith.  in this case you would expect that different bounded contexts use different classes/models to represent the different versions of, eg `Product` or `Batch`.

i hasten to add that i have never personally done this, so I don't have any lived experience of this to refere to. but i imagine that the "purist" way of doing it would be to actually store the different models in different tables.  then maybe you could use internal events as a way of synchronising between the two?  and that will leave you with the problem of needing to think carefully about transactions.

alternatively your ORM/repository would be the place where you can query a single table, but do the filtering and transformations necessary to produce the different models for each context.  that sounds fairly manageable from a read point of view, but you'd have to be very careful about how you manage writing...

**Comment by simkimsia** [comment]
Thanks for reply, @hjwp 

> am assuming that by "datatable" you mean a table in a database, is that right?
Yes

Sorry but I want to move away from the earlier fictitious example in favor of this one from Martin Fowler for better way to express my thoughts

in boundedcontexts https://martinfowler.com/bliki/BoundedContext.html using the same example as Fowler

![diagram](https://martinfowler.com/bliki/images/boundedContext/sketch.png)

You can have Customer and Product in more than 1 bounded contexts.

> i hasten to add that i have never personally done this

By this, you mean?

a) different bounded contexts (as defined above in the fowler diagram) within the same app/monolith OR
b) store the different contextual but overlapping models in different tables which essentially are [multiplecanonicalmodels](https://martinfowler.com/bliki/MultipleCanonicalModels.html) meaning to say we will have a sales_product table that the SalesProduct model can access within the Sales context and another support_product table that the SupportProduct model can access within the Support context. And a single unique product can appear in both tables as unique records.

Apologies that I have to ask to such fine details. But as you're probably aware, good software engineering requires more [splitting than lumping](https://martinfowler.com/bliki/MultipleCanonicalModels.html)

**Comment by hjwp** [comment]
I have done neither!     So I'm really not in a good position to give advice.  maybe sharing classes and database tables across bounded contexts is _just fine_.  or maybe it's an acceptable tradeoff in some circumstances...

I wonder if there might be some good info on this in the red book (vernon/implementing ddd)

**Comment by simkimsia** [comment]
Oh interesting... 

So using the batch allocation example in the cosmic book

Are you sayingin MADE highly common domain entities like Product that appear in different contexts eg e-commerce and allocation ... you will always have the contexts as separate apps?

**Comment by hjwp** [comment]
mostly, yes.  each app has its own database.  we have an app that's in charge of of product information, and emits comprehensive events describing new products or changes to data about existing products, and then other apps listen to those events, and pick and choose which attributes they care about.  one might care about price and description.  another might care about size and weight.  etc.

**Comment by simkimsia** [comment]
I think this plus my question abt external message bus (see #306) solves this issue

**Comment by hjwp** [comment]
:-)
