### ISSUE TITLE
[Feedback] on the website can you make it easier to obtain the subssecton links?

### ISSUE THREAD

**Issue by simkimsia** [cosmicpython/book#295]
for issue #294 i had to cite this section https://www.cosmicpython.com/book/chapter_07_aggregate.html#bounded_contexts_sidebar

The way I did it was to actually read the source and then notice the id tag in the div element.

Instead of doing that can you make it easy for us to obtain it via clicking alone?

not crucial but it's a small nice UX improvement :)

Thank you!~

**Comment by hjwp** [comment]
yes! i want these too.

**Comment by hjwp** [comment]
wow looks like it would actually be really simple https://mrhaki.blogspot.com/2014/05/awesome-asciidoc-turn-section-titles.html

**Comment by simkimsia** [comment]
Love it! 🙌
