### ISSUE TITLE
Development environment with Pycharm

### ISSUE THREAD

**Issue by jhagege** [cosmicpython/book#296]
Hi, I'm trying to follow along with Pycharm. 
Can you recommend a good setup so that I can run the tests dynamically and have a proper debugging environment ? 
I did make build and make up but I can't connect from Pycharm with Docker Python interpreter.
Thanks for your insights !

**Comment by jhagege** [comment]
Amazing book so far by the way :)

**Comment by hjwp** [comment]
hey!  you should be able to run the tests from a local python virtualenv just by running `pytest tests/unit` (and `tests/integration` and `tests/e2e`). there's a `requirements.txt` in the root.  let me know if that works?

**Comment by jhagege** [comment]
Works great, thanks much !

**Comment by jhagege** [comment]
@hjwp actually, I wanted to have debug environment as well in the flask_app, and not only in the test code, so sharing here the configuration that worked for me in Pycharm, in case it can help anyone.
If you can think of a better pattern, happy to hear.

![Screen Shot 2020-04-29 at 15 33 29](https://user-images.githubusercontent.com/7504908/80596383-f1517e80-8a2e-11ea-8416-6af3fc5a7374.png)

![Screen Shot 2020-04-29 at 15 34 03](https://user-images.githubusercontent.com/7504908/80596391-f3b3d880-8a2e-11ea-9823-90562c96814a.png)

![Screen Shot 2020-04-29 at 15 34 13](https://user-images.githubusercontent.com/7504908/80596393-f44c6f00-8a2e-11ea-8799-9de9adb98592.png)

**Comment by hjwp** [comment]
cool!  what does that let you do?

**Comment by jhagege** [comment]
Able to launch the Flask app in debug mode, and put breakpoints on the API entrypoints. 
Unless I did some mistake, breakpoints at API entrypoint are not caught when running tests from local venv, even in debug mode. 
Makes sense ?

**Comment by hjwp** [comment]
yep!  am with you.

I guess i'm hoping that flask becomes such a thin wrapper that I never need to put a breakpoint in it :wink:
