### ISSUE TITLE
[Question] will you version or tag this repo?

### ISSUE THREAD

**Issue by simkimsia** [cosmicpython/book#297]
Hi there, 

Just a question, will you version or tag release this repo?

I bought the book and wrote many ad hoc post it notes on it.

But my compiled notes are digital. When I refer to the repo in the compiled notes, I think it's best for me to refer to an actual version or release version of this repo. Can advise?

**Comment by hjwp** [comment]
good idea!  i've pushed a tag that's as close as i can get to the version that was released to print: https://github.com/cosmicpython/book/releases/tag/v1.0
