### ISSUE TITLE
[Question] so you need one AbstractRepository for every domain entity?

### ISSUE THREAD

**Issue by simkimsia** [cosmicpython/book#298]
I'm looking to implement this https://www.cosmicpython.com/book/chapter_02_repository.html#_the_repository_in_the_abstract

then i notice that you explicitly declare that the get and add is looking out for Product entity.

Does that mean you need an abstract repository for *every* domain entity? Isn't that a bit overkill in terms of boilerplate?

**Comment by hjwp** [comment]
you need a (real) repository for each aggregate, for sure, but i reckon you could probably get away with one shared abstract repository for all of them, sure.

**Comment by hjwp** [comment]
for the type hints to work you'd probably want to define some base `class Aggregate`...

**Comment by simkimsia** [comment]
sorry could you elaborate a bit more abt this line?

> for the type hints to work you'd probably want to define some base `class Aggregate`

This base class is for the real repository to inherit from?  or something else?

**Comment by hjwp** [comment]
no for your domain model aggregates to inherit from.  we often have a base class for `Entity`, `Aggregate` and sometimes `ValueObject`.
