### ISSUE TITLE
Issue with domain object not bounded to a Session

### ISSUE THREAD

**Issue by Tserewara** [cosmicpython/book#317]
I'm implementing a personal project using the examples of the book. It has been great so far. But, in one of my usecases, which is retrieving all the entries using the UOW pattern, the session is apparently closed before I can query the objects. The tests in the unit of work pass, but my e2e test doesn't. 

Here's my service:

```py
def list_entries(uow: unit_of_work.AbstractUnitOfWork) -> List[model.Entry]:

    with uow:
        entries = uow.entries.list()

        if not entries:
            raise model.NoEntries('No entries were found')

    return entries
```
And here's my entrypoint:

```py
@app.route('/entries')
def get_entries():
    try:

        entries = services.list_entries(
            unit_of_work.SqlAlchemyUnitOfWork()
        )

        serialized_entries = serializers.serialize_entry(entries, many=True)

        return jsonify(serialized_entries), 200

    except model.NoEntries:
        return jsonify([]), 400
```

The only way I could make it work was by removing the `self.session.close()` from my `SqlAlchemyUnitOfWork`. But this doesn't feel right. How should I handle this correctly?

**Comment by hjwp** [comment]
when does the session get opened?  it needs to happen whenever you go into a new unit of work, so probably in `__enter__()`.

for clarity we sometimes separate out two classes, a `UnitOfWorkManager` to hold all the config, and a separate  `UnitOfWork` to be a short-lived context manager.  then it can be a bit clearer to see the lifecycle...

**Comment by Tserewara** [comment]
Here's the implementation of my uow as in the book. I commented the line that closes the session so it works. My question is if this is right.

```py
class SqlAlchemyUnitOfWork(AbstractUnitOfWork):

    def __init__(self, session_factory=DEFAULT_SESSION_FACTORY):
        self.session_factory = session_factory

    def __enter__(self):
        self.session = self.session_factory()  # type: Session
        self.entries = repository.SqlAlchemyRepositoryEntries(self.session)
        self.categories = repository.SqlAlchemyRepositoryCategories(
            self.session)
        return super().__enter__()

    def __exit__(self, *args):
        super().__exit__(*args)
        # self.session.close()

    def commit(self):
        self.session.commit()

    def rollback(self):
        self.session.rollback()

```

In my service layer, I have a `service.py` file, and the function `list_entries`. My flask route, as I placed the code above calls the service, then it raises the error I mentioned. I understand that when the context finishes, the session is closed. But why can't the context return the result of `list_entries` even though I return it as you can see in the code? Aren't the results simple Python objects? Shouldn't they be returned as so, even though they are not bounded to a session?

I don't know if my question makes sense or if I am making some obvious mistake. Anyway, thank you so much for the response.

By the way, the book is mindblowing. I couldn't thank you enough for it. I'm happy I could find and buy the digital version.

**Comment by hjwp** [comment]
ah i've seen this error before.  no, once the SQLAlchemy ORM touches an object it becomes special, and if you try to access certain properties on it after the session has been closed, it complains.  it's to do with enabling lazy attribute lookups or something?

(this kind of annoyance is one of the things that turned me off ORMs tbh.  in recent projects we've just been using raw SQL)

anyways, one solution might be to bring the serializer inside the application?  i think you could qualify it as being an "adapter" of some kind.  

oh yes and the other option is to say:  read-only views don't need to use the Domain Model, or the Unit of Work, at all!    after all, you only need a UoW if you're actually going to make changes.  Have a read of the CQRS chapter?

**Comment by Tserewara** [comment]
Great insights! Thank you so much. About the ORM, I began to think of using raw SQL since I started reading the book. I haven't tried that before because I was afraid I would end up with a lot of SQL spread through my code. But now, I understand exactly where to put things. 

It's excellent to know that I don't need to use the Domain Model and uow for read-only views! It makes a lot of sense. In this case, should I get the objects direct from the repo? What if I need some kind of filter as my business rule? Should I create a service in this case, or use the same approach for read-only views?

I'm sorry for so many questions, but I'm pretty excited about the book.

I'm eager to read the next chapters! (Just finished chapter 6)

**Comment by hjwp** [comment]
Glad you're enjoying it!  remember to write a review on amazon or goodreads or wherever, those really help.

yep you can go directly to the repo, or even bypass that too and go directly to the db.  read the CQRS chapter!  it's ok to skip ahead now and again...

be aware that raw SQL can be a source of major problems too.  like the way that postgres handles `IS NULL` vs `= NULL` is very different and could be a major cause of unexpected bugs lol ask me how i know this.

**Comment by lucassus** [comment]
@Tserewara as a workaround you could try enable eager loading mechanism. Eg:

```python
def start_mappers():
    mapper(
        Project,
        projects,
       
        # This will eager load tasks in a separate sql query
        properties={
            "tasks": relationship(Task, order_by=tasks.c.id, lazy="immediate"),
        },
    )

    mapper(Task, tasks)
```

```python
def test_session(db_engine):
    session_factory = sessionmaker(bind=db_engine)
    session = session_factory()

    project = session.query(Project).get(1)
    session.close()

    assert project
    assert len(project.tasks) == 1
```

When you are creating an objects, before closing the session you could try to refresh the instance. Eg:

```python
def test_session(db_engine):
    session_factory = sessionmaker(bind=db_engine)
    session = session_factory()

    project = Project(name="Testing")
    session.add(project)
    session.commit()

    session.refresh(project)
    session.close()

    assert project
    assert len(project.tasks) == 1
```

**Comment by lucassus** [comment]
I have one more solution in my mind. Instead of returning sqlalchemy instance from your service (that uses uow or bare session) you could return "serialized" results. Assuming that you use pydantic, you could have something like that:

```python
# ...

project = session.query(Project).get(1)
serialized_project = schemas.Project.from_orm(project)
session.close()

return serialized_project
```

But it feels to me like mixing responsibilities, since this kind of serialization should be done in the other layer (like api entrypoints).

**Comment by xtaje** [comment]
Another way to think about the lazy vs eager-loading issue about it is that the ORM is mapping an object-graph to tables-and-relations.  If you're holding onto a piece of that graph, and do something that requires the whole graph (like serialization), you've either got to have the whole thing in memory already, or an open session so that the ORM can grab the rest of it.

Another easy fix is to do something like this:
> 
> ```python
> @app.route('/entries')
> def get_entries():
>     try:
>         with unit_of_work.SqlAlchemyUnitOfWork() as uow:
>            entries = services.list_entries(uow)
> 
>            serialized_entries = serializers.serialize_entry(entries, many=True)
> 
>            return jsonify(serialized_entries), 200
> 
>     except model.NoEntries:
>         return jsonify([]), 400
> ```
And adjust `services.list_entries`.  In the book, the uow scope is associated with a command, whereas in this snippet, it's associated with a request.  The book is more ideologically "right", but there shouldn't be a difference as long as you handle one command per request.  I think the risk is that someone will be tempted to just start calling a bunch of handlers that operate on different aggregates, at which point the domain model starts to break down.

**Comment by Tserewara** [comment]
@hjwp I did the review, it must be published soon! Finally I got some time to dive into the CQRS chapter! Thanks!

**Comment by Tserewara** [comment]
@lucassus Thank you for the insights. I tried to apply your suggestion of changing the loading method, but it didn't work for me. I must be doing something wrong. I need to learn more about this. About returning the serialized objects, I was wondering exactly if it was in the right layer, since it seems to be the entrypoint's responsability. Anyway, accessing the objects directly from the entrypoint without the uow, as @hjwp said, seems to be a great solution.

**Comment by Tserewara** [comment]
@xtaje Thank you, I believe that's a great solution. Actually, this was my first try before I opened the issue, but I wasn't sure if it was right, since I had created a service for that. But now, it makes sense to me.

**Comment by lucassus** [comment]
@Tserewara CQRS could be another solution for that problem. For instance instead of returning a  serialized record (which somehow breaks single responsibility rule) you could just redirect to `GET /some/resource/:id` endpoint. Here you could find an example of such approach https://github.com/lucassus/fastapi-sandbox/blob/ebfd93c461/todos/services/project_management/entrypoints/routes/project_tasks.py#L17
I think that it works pretty well and it's super easy to maintain.

BTW. I would be glad if someone could take a look at this project and give me some feedback ;)
