### ISSUE TITLE
Validation Appendix

### ISSUE THREAD

**Issue by hjwp** [cosmicpython/book#32]
1. event/command schemas
2. at service layer
3. in model (business rules)
4 (?) at other exit boundaries?

**Comment by bobthemighty** [comment]
Sketch out a new chapter. Discuss:

* Validate at the edges
* Difference between syntax and semantics
* Discuss patterns for validating messages
* Talk about reasons for loosely validating messages in the consumer, tolerant reader et c.

**Comment by hjwp** [comment]
this is in progress, track via todos in [actual chapter](/cosmicpython/book/appendix_validation.asciidoc)
