### ISSUE TITLE
Question - Repository Pattern without UoW

### ISSUE THREAD

**Issue by julianomontini** [cosmicpython/book#320]
Hello!
First of all, thanks for the awesome book, its rare to see someone talking about architecture and best practices without providing any actual examples.

I'm really trying to implement the repository pattern, because it's something that held the unit tests in other projects, and in the end, the whole system was depending on Hibernate.

Where should I manage the Repository session when now using UoW? If I create the session inside my service or gateway ( controller ), then I'm relying on the implementation, and for some use cases that I have in mind, this is specifically bad, because if we have a database that doesn't support sessions (eg: AWS DynamoDB), then I must remove the code to create sessions. Any ideas on how to manage that? Or even how to name that?

**Comment by hjwp** [comment]
> Where should I manage the Repository session when not using UoW?

this is approximately the situation in chapter 4 of the book.  I'd say create the session as close to the "outside" of your system as possible -- in the book, I create it in `flask_app.py`, which is outside of the service layer.

https://github.com/cosmicpython/code/blob/chapter_04_service_layer/flask_app.py

that way the core of our application code, the domain and the service layer, are not involved in creating the session.

does that help?  I can't be sure what you mean by "gateway" or "controller"...

**Comment by julianomontini** [comment]
Yes, it does help, but I'm not too happy with this approach, because:
1 - I need to create the session in every single endpoint that uses it
2 - My service now knows details about the implementation of my repository (eg: session and commit are required)

Instead, what I did was:

```
class ServiceFactory:
    @classmethod
    def todo(cls):
        session = AlchemySessionFactory.get_session()
        repo = AlchemyTodoRepository(session)
        return TodoService(repo)
```

and

inside app route:
```
from service_factory import ServiceFactory
...
todo_service = ServiceFactory.todo()
...
```

Any thoughts on this?

**Comment by hjwp** [comment]
looks pretty nice to me!  apart from the word `Factory`, i have an irrational dislike of those lol.

**Comment by julianomontini** [comment]
@hjwp Even my IDE is complaining about it haha. I could use a single function for that, but I understand your precaution when using "factories", because its easy to shove everything in there. Anyway, thank you for the fantastic support! :)

**Comment by hjwp** [comment]
Hope it's ok if i close this issue then!

do feel free to get in touch if you have any more questions, am happy to help.

oh if you get a second, will you write a review of the book? on amazon or goodreads or wherever you like to post reviews?  they really help...
