### ISSUE TITLE
Book website is "broken"

### ISSUE THREAD

**Issue by laurent-jakubina** [cosmicpython/book#344]
The book website is broken: 

![image](https://user-images.githubusercontent.com/100640135/235811993-f254cbb5-a8b9-4e4f-af41-15e696305dd9.png)
See: https://www.cosmicpython.com/

**Comment by hjwp** [comment]
oh gawd.

**Comment by hjwp** [comment]
@bobthemighty

**Comment by ljak** [comment]
Website is back. Fixed ?
