### ISSUE TITLE
'Bug' in Chapter 9 with the `FakeUnitOfWorkWithFakeMessageBus`

### ISSUE THREAD

**Issue by programmer-ke** [cosmicpython/book#350]
When introducing the `FakeUnitOfWorkWithFakeMessageBus`, the idea is to intercept events processing by the message bus and record them instead.

However, in the book text, this is done by overriding the `publish_events` method, which had earlier been replaced by `collect_new_events` in the base class, so it doesn't have an effect and the test fails.

I achieved the desired outcome by instead overriding `collect_new_events` like so:

```python
class FakeUnitOfWorkWithFakeMessageBus(FakeUnitOfWork):

    def __init__(self):
        super().__init__()
        self.events_published = []  # type: List[events.Event]

    def collect_new_events(self):
        for product in self.products.seen:
            while product.events:
                event = product.events.pop(0)
                self.events_published.append(event)
                yield event
```

Great book otherwise, thanks!

**Comment by hjwp** [comment]
good catch, thanks!

by some coincidence, another person raised this exact issue just recently too https://github.com/cosmicpython/code/issues/83

**Comment by programmer-ke** [comment]
> good catch, thanks!
> 
> by some coincidence, another person raised this exact issue just recently too [cosmicpython/code#83](https://github.com/cosmicpython/code/issues/83)

Oh! I missed that issue. I'll close this one then.
