### ISSUE TITLE
use a slightly more nested folder structure

### ISSUE THREAD

**Issue by hjwp** [cosmicpython/book#64]
around chapter 3/4/the project structure appendix, the tree would look like this:

```
│   ├── allocation
│   │   ├── adapters
│   │   │     └── flask_app.py
│   │   ├── config.py
│   │   ├── domain_model.py
│   │   ├── infrastructure
│   │   │     ├── orm.py
│   │   |     └── repository.py
│   │   └── services.py
```

by the end, it would look like this:

```
│   ├── allocation
│   │   ├── bootstrap.py
│   │   ├── config.py
│   │   ├── domain_model
│   │   │   ├── commands.py
│   │   │   ├── events.py
│   │   │   └── model.py
│   │   ├── entrypoints
│   │   │   ├── flask_app.py
│   │   │   └── redis_eventconsumer.py
│   │   ├── adapters
│   │   │   ├── email.py
│   │   │   ├── orm.py
│   │   │   ├── repository.py
│   │   │   └── redis_pubsub_client.py
│   │   ├── service_layer
│   │   │   ├── exceptions.py
│   │   │   ├── messagebus.py
│   │   │   ├── handlers.py
│   │   │   └── unit_of_work.py
```

**Comment by hjwp** [comment]
or `entrypoints` and `adapters`?

```
│   ├── allocation
│   │   ├── entrypoints
│   │   │   ├── flask_app.py
│   │   │   └── redis_pubsub.py
│   │   ├── bootstrap.py
│   │   ├── config.py
│   │   ├── domain_model
│   │   │   ├── commands.py
│   │   │   ├── events.py
│   │   │   └── model.py
│   │   ├── exceptions.py
│   │   ├── handlers.py
│   │   ├── messagebus.py
│   │   ├── adapters
│   │   │   ├── email.py
│   │   │   ├── orm.py
│   │   │   ├── repository.py
│   │   │   └── unit_of_work.py
```

**Comment by pedroabi** [comment]
I suppose that allocation is a bounded context. If I have another context like, orders for e..g, should I have another folder called orders with th same structure as allocation?
And how should avoid code duplication? For e.g. UOW should be very similar.

**Comment by hjwp** [comment]
excellent question!

it depends if you're in a microservices environment or in a monolith.  we've mostly written the book assuming microservices, so each bounded context is a totally separate application + repository + deployment.

a monolith is a perfectly valid architectural choice too, and you can absolutely do DDD in a monolith, and yes, folder structure sounds like a good way to make that distinction clear.  I don't personally have any direct experience of it, but we're looking to talk about it a bit in the final/epilogue chapter...

**Comment by hjwp** [comment]
re where to put uows and deduplicate, am sure you can figure something out. uows would have different repositories for different contexts, but some sort of shared base class could be useful.

**Comment by pedroabi** [comment]
We have been using a monolith architecture with a 3 years project e-commerce. It was entirely developed in Python + AWS Lambda + GraphQL. O coukd point some engineers to talk about the theme.

**Comment by hjwp** [comment]
i'd be very interested to hear you + your team's reaction to the book - particularly any remaining questions, like this, "how does it work in a monolith" - it will help us write the final chapter...

**Comment by hjwp** [comment]
done-a-saurus.
