### ISSUE TITLE
Choose a good title

### ISSUE THREAD

**Issue by hjwp** [cosmicpython/book#72]
throw your suggestions in here folks!   Here's our current two front-runners in the "fun" and "boring" slots:

### Cosmic Python

_Managing Complexity using Architectural Patterns, from DDD to Ports & Adapters_

(because _cosmos_ is the opposite of _chaos_.  don't take my word for it, trust [carl sagan](https://www.goodreads.com/quotes/604655-cosmos-is-a-greek-word-for-the-order-of-the).  don't worry, we'll explain it in the blurb...)

----

### Managing Application Complexity with Python

_Classic Enterprise Architecture Patterns, from DDD to Ports & Adapters, made Pythonic_

----

**Comment by hjwp** [comment]
(because _cosmos_ is the opposite of _chaos_.  don't take my word for it, trust [carl sagan](https://www.goodreads.com/quotes/604655-cosmos-is-a-greek-word-for-the-order-of-the).  don't worry, we'll explain it in the blurb...)

**Comment by moreati** [comment]
please not the second one. It's a _lot_ easier to remember/recommend a 2 word locator/identifier, should the book come up in conversation, or get name dropped in an article/presentation. I don't remember what your testing book is called, I damn well remember "testing goat".

**Comment by luistm** [comment]
Please, use Cosmic Python :)

**Comment by c00kiemon5ter** [comment]
Cosmic Python sound nice; short and fun 👍

**Comment by Pilifer** [comment]
Cosmic Python is very good. What animal could be the symbol of order? Could you use ptolemaic celestial spheres as a symbol? https://upload.wikimedia.org/wikipedia/commons/3/3a/Ptolemaicsystem-small.png

**Comment by rbricheno** [comment]
> 
> 
> What animal could be the symbol of order? 

Surely an [ouroboros](https://en.wikipedia.org/wiki/Ouroboros)

**Comment by hjwp** [comment]
thanks for the support everyone! hopefully it'll help convince our editor :😉

**Comment by shaunickmistry** [comment]
Managing Application Complexity with Python sounds a lot like other books, which means people will feel they've read this before.

Cosmic Python is memorable, striking and fits the convention of other books from Made.

**Comment by meshaabi** [comment]
Managing Application Complexity with Python though makes great google search keywords for discovery.

**Comment by luistm** [comment]
COSMIC PYTHON - Managing Application Complexity

**Comment by hjwp** [comment]
In the end, negotiations with OR have resulted in:

*Architecture Patterns with Python*
_Enabling Test-Driven Development, Domain-Driven Design, and Event-Driven Microservices_

so it's not fun and the subtitle is a bit kitchensink but it's reasonably explicit.
