### ISSUE TITLE
Use data classes to a full potential

### ISSUE THREAD

**Issue by enkidulan** [cosmicpython/book#87]
Reading thru [chapter 1](https://github.com/python-leap/book/blob/5abd3d714e17cdf8edf99691f68506f0e30a99cd/chapter_01_domain_model.asciidoc) I've noticed that some classes, like `OrderLine`, are data classes and some are not. It may worth considering to use data classes more to be more consistent. Also having all classes as data classes will make code more declarative. 

For example `Batch` class:
 
```python
class Batch:
    def __init__(
        self, ref: str, sku: str, qty: int, eta: Optional[date]
    ):
        self.reference = ref
        self.sku = sku
        self.eta = eta
        self._purchased_quantity = qty
        self._allocations = set()  # type: Set[OrderLine]

    def __repr__(self):
        return f'<Batch {self.reference}>'

    def __eq__(self, other):
        if not isinstance(other, Batch):
            return False
        return other.reference == self.reference

    def __hash__(self):
        return hash(self.reference)

    def __gt__(self, other):
        if self.eta is None:
            return False
        if other.eta is None:
            return True
        return self.eta > other.eta
```
can be declared as `dataclass` and it'll save some lines of code:
```python
@dataclass(unsafe_hash=True)
class Batch:
    reference: str = field(hash=True)
    sku: str = field(compare=False)
    quantity: int = field(compare=False)
    eta: datetime = field(compare=False, default=None)
    allocations: Set[Line] = field(compare=False, default_factory=set, init=False)

    def __gt__(self, other):
        if self.eta is None:
            return False
        if other.eta is None:
            return True
        return self.eta > other.eta
```

**Comment by hjwp** [comment]
Thanks Max!  several features of dataclasses there that I didn't know existed :)

will have a think.  at the moment i quite like the conceptual distinction where "dataclasses are for value objects, entities are just plain old classes"

**Comment by enkidulan** [comment]
Yep, `dataclasses` looks like a step forward comparing to `namedtuple`, but their usage is not limited only to value objects. Probaly most controversial thing here is that `dataclasses`, unlike `namedtuple`, are not memory effective and you can't define `__slots__` on them easily.

**Comment by hjwp** [comment]
run out of time for this really.  for the 2e!
